name: FASTO
favicon: null
layout_spectrum: 0.2454
typography_spectrum: 0.53864
title: estates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#83684e'
    - '#a4917f'
    - '#c8c0b9'
    - '#d1a681'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: awareness
    item: null
    url: null
